version: '3'

includes:
  cargo:
    taskfile: mono-dev/task/cargo.yaml
    optional: true
    interal: true

tasks:
  install:
    - rm -rf mono-dev
    - git clone https://github.com/Pistonight/mono-dev --depth 1

  build-lib:
    - cargo build --no-default-features

  check:
    - task: cargo:clippy-all
    - task: cargo:fmt-check
    - cargo run

  test:
    - cargo test
    - task: test-inline-cmd

  test-fixt:
    - cargo test --test fixture_test

  test-inline-cmd:
    dir: src
    cmds:
      - cargo run -- -H Pistonite -L MIT **/*.rs

  fix:
    - cargo run -- -f
    - task: cargo:fmt-fix
    - task: check

  clean:
    - cargo clean
    - rm -f tests/fixtures/*.txt_out
    - rustup update
